name: abg_utils
description: Utils for ABG projects
version: 8.0.9

homepage: https://www.abg-studio.com

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  razorpay_flutter_31: ^1.3.2
  flutter_paystack: ^1.0.5+1
  http_auth: ^1.0.1

  csv: ^5.0.0
  qr_flutter: ^4.0.0
  pdf: ^3.6.4

  cloud_firestore: ^3.1.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_messaging: ^11.4.4
  flutter_app_badger: ^1.3.0

  #sign_in_with_apple: ^3.0.0
  #google_sign_in: ^5.2.1
  #google_sign_in_web: ^0.10.0+3
  google_maps_webservice: ^0.0.20-nullsafety.5

  connectivity_plus: ^2.2.0
  device_info_plus: ^3.2.1
  auto_size_text: ^3.0.0
  shared_preferences: 2.0.13
  flutter_colorpicker: ^0.6.0
  matrix4_transform: ^2.0.1
  flutter_html: ^2.2.1
  js: ^0.6.3
  timeago: ^3.1.0
  universal_html: ^2.0.8
  geolocator: ^8.1.1
  firebase_storage: ^10.1.0
  uuid: ^3.0.5
  google_maps_flutter: ^2.0.3
  maps_toolkit: ^2.0.0
  path_provider: ^2.0.8
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.18
  archive: ^3.1.6
  http: ^0.13.4
  webview_flutter: ^2.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

flutter:
  assets: # использовать так Image.asset("assets/noimage.png", package: 'abg_utils', fit: BoxFit.contain,)
    - assets/
    - assets/noimage.png
    - assets/elements/
